# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyingclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aeroplanes',
            options={'verbose_name_plural': 'aeroplanes'},
        ),
        migrations.AlterModelOptions(
            name='aeroplanesavailabilityerrors',
            options={'verbose_name_plural': 'aeroplanes_availability_errors'},
        ),
        migrations.AlterModelOptions(
            name='amends',
            options={'verbose_name_plural': 'amends'},
        ),
        migrations.AlterModelOptions(
            name='flights',
            options={'verbose_name_plural': 'flights'},
        ),
        migrations.AlterModelOptions(
            name='forecastmaintanancecompleted',
            options={'verbose_name_plural': 'forecast_maintanance_completed'},
        ),
        migrations.AlterModelOptions(
            name='forecastmaintanancelist',
            options={'verbose_name_plural': 'forecast_maintanance_list'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'members'},
        ),
        migrations.AlterModelOptions(
            name='membersroles',
            options={'verbose_name_plural': 'members_roles'},
        ),
        migrations.AlterModelOptions(
            name='membersstatuserrors',
            options={'verbose_name_plural': 'members_status_errors'},
        ),
        migrations.AlterModelOptions(
            name='serviceability',
            options={'verbose_name_plural': 'serviceability'},
        ),
    ]
